### ISSUE TITLE
Errata when changing resolutions during startup

### ISSUE THREAD

**Issue by Blobanium** [Blobanium/Loading-Timer#11]
Extended From #9 as another issue was discovered

**Comment by Blobanium** [comment]
i probably removed the safeguard entirely bc it pretty much didn't work well. safe to close.

**Comment by K0-RR** [comment]
So, what about this issue?
![image](https://user-images.githubusercontent.com/43277609/114286602-9d358380-9a60-11eb-862a-43fd544d7d6e.png)

**Comment by Blobanium** [comment]
is this the latest version of the mod?

**Comment by K0-RR** [comment]
Yes, 1.3-Beta1

**Comment by Blobanium** [comment]
reopening this as this seems to be a confirmed bug. ill look into this.

**Comment by Blobanium** [comment]
i tested the workaround myself and the bug should be fixed. I also made it so that would log an error saying to refrain from changing resolutions during startup. (id probably want to change this to log a warn instead of an error)

**Comment by Blobanium** [comment]
anyways closing this thread (again) as the bug seems to be fixed, hopefully.
