### ISSUE TITLE
"Minecraft took X seconds to initialize." is the same as "... fully load" with Architectury.

### ISSUE THREAD

**Issue by K0-RR** [Blobanium/Loading-Timer#12]
```
[22:40:18] [main/INFO]: [STDOUT]: Minecraft took 40.128 seconds to fully load.
[22:40:18] [main/INFO]: [STDOUT]: That is 28.524 seconds worth of raw loading time
```

Sometimes there are only these two lines

**Comment by Blobanium** [comment]
do you have a log? (Just to make sure that they are loading properly)

**Comment by K0-RR** [comment]
This is so weird - it IS printing with Architectury and ISN'T without it.

**Comment by Blobanium** [comment]
You might wanna try scrolling up in the log by a little bit. Most likely an invalid issue.

**Comment by K0-RR** [comment]
> You might wanna try scrolling up in the log by a little bit. Most likely an invalid issue.

Renamed

First log is without Architectury, the second with.
https://paste.ee/p/pzOAz
https://paste.ee/p/nov7l

**Comment by Blobanium** [comment]
![Capture](https://user-images.githubusercontent.com/45613796/110259897-d315b280-7f5e-11eb-9b4d-dc9d29ad953e.PNG)

yup it seems to be working properly.

**Comment by Blobanium** [comment]
most likely an invalid issue, as this seems to be working as intended
also most likely caused by #10 probably if that's what your talking about
