### ISSUE TITLE
Mod updater support.

### ISSUE THREAD

**Issue by K0-RR** [Blobanium/Loading-Timer#13]
I saw you added support for Vanguard and found it weird that not for ModUpdater which is more popular and older. Also, the name makes sense.
https://www.curseforge.com/minecraft/mc-mods/modupdater

**Comment by Blobanium** [comment]
ok ill look into ModUpdater and see what i can do with it.

**Comment by Blobanium** [comment]
closing this as now this should be in v1.2.4
