### ISSUE TITLE
AutoUpdate is bad for Modpacks

### ISSUE THREAD

**Issue by dandin87** [Blobanium/Loading-Timer#20]
Forcing an autoupdate mod which could also update any number of other mods that also use Vanguard is a very bad idea for modpacks. If users want to use Vanguard you should link to it, instead of jar in jar'ing it. We would have liked to include this, but you can't have mods auto updating in a modpack, and it could prevent players from accessing the server. This mod obviously is not going to affect that, but by including Vanguard you are enabling Auto Updates for any mod that supports it.

**Comment by Blobanium** [comment]
apologies if i have grammar issues. I will push a commit here in a second that will un-jnj vanguard. I really didn't know that nesting vanguard into my mod is such a bad idea.
