### ISSUE TITLE
[Request] Show the timer for resource reloads as well as the initial game load

### ISSUE THREAD

**Issue by frugbug** [Blobanium/Loading-Timer#23]
I am a resource pack maker, and it would be nice to know how long a resource reload took.

**Comment by Blobanium** [comment]
Closing this thread as this has now been added as of commit https://github.com/Blobanium/Loading-Timer/commit/f37b91f47a0d503613f7de0bd7ffbe1f62075af2. (I made this as an option if you want to enable or disable this.(its disabled by default)) Heres this link if u want to read more about it: https://github.com/Blobanium/Loading-Timer/wiki/Config-Guide#resource-loading-notification
