### ISSUE TITLE
Doesn't work with 1.18.2

### ISSUE THREAD

**Issue by srnyx** [Blobanium/Loading-Timer#34]
https://paste.srnyx.xyz/mucexukiru.properties

**Comment by Blobanium** [comment]
use https://github.com/Blobanium/Loading-Timer/actions/runs/2012774123

**Comment by srnyx** [comment]
> use [Blobanium/Loading-Timer/actions/runs/2012774123](https://github.com/Blobanium/Loading-Timer/actions/runs/2012774123)

Aha, just realized there were multiple branches. When do you plan on releasing to CurseForge?

**Comment by srnyx** [comment]
Just used the build you sent me, I'm getting a similar error: https://paste.srnyx.xyz/elofikoteg.properties

**Comment by Blobanium** [comment]
> Just used the build you sent me, I'm getting a similar error: https://paste.srnyx.xyz/elofikoteg.properties

it seems that the issue might be that if the mixin is failing to expose the bootstrap method properly, may be either an issue between either yarn or spongepowered idk. Or it might be that im an idiot and it may or may not be something on my end.

Gonna reopen this issue for the time being. If you can find a way for this to work, feel free to make a PR.

**Comment by Julienraptor01** [comment]
this mod is able to count the launch time so maybe you can get some inspiration or help by the dev ?
https://modrinth.com/mod/dashloader

**Comment by Phoenix-Starlight** [comment]
The refmap is not being automatically added, which means you have to manually edit the jar for one.
