### ISSUE TITLE
1.19 update please:)

### ISSUE THREAD

**Issue by ghost** [Blobanium/Loading-Timer#38]

**Comment by Phoenix-Starlight** [comment]
Have you tried testing whether overriding the dependency works?
https://fabricmc.net/wiki/tutorial:dependency_overrides

**Comment by SunnySlopes** [comment]
i've fixed the problem and ported it to 1.19, you can check it in my folk

**Comment by ghost** [comment]
Hello @SunnySlopes, thank you so much for the port 🥰
